version: '3.8'
services:
  node:
    container_name: app-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
